### ISSUE TITLE
Application.yml template should ignore values that are in an environment it's not creating

### ISSUE THREAD

**Issue by samsonasu** [tenforwardconsulting/subspace#159]
```
# application.yml.template
MY_SECRET: {{MY_SECRET}}

production: 
  PROD_ONLY: {{PROD_ONLY}}

dev:
  DEV_ONLY: {{DEV_ONLY}}
```

```
# vars/dev.yml
MY_SECRET: some_secret_value
DEV_ONLY: other_secrete_value
```

if you run `subspace vars dev --create` this will fail because the template references `PROD_ONLY` which isn't present in `vars/dev.yml`
