### ISSUE TITLE
`init` adds extra block to playbook

### ISSUE THREAD

**Issue by petitJAM** [tenforwardconsulting/subspace#42]
```
  - hosts: localhost
    connection: local
    gather_facts: False

    vars_files:
      - vars/aws.yml

    roles:
      - { role: aws, hostname: stimmi-production }
```

`subspace init` adds this to `provision/env.yml` above the real block that we want.
